spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contract_manager
    username: contract_user
    password: contract_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.security: DEBUG