spring:
  application:
    name: contract-manager-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/contract_manager
    username: contract_user
    password: contract_pass

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: validate
    show-sql: true
    open-in-view: false
